import { Inter, Lexend_Deca } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { Web3ProviderContextProvider } from "@/context/Web3ProviderContext";

const inter = Inter({ subsets: ["latin"] });
const lexend = Lexend_Deca({ subsets: ["latin-ext"] });


export const metadata = {
  title: "Tangled",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={lexend.className}>
        <Web3ProviderContextProvider>
          <Navbar />
          {children}
        </Web3ProviderContextProvider>
      </body>
    </html>
  );
}
